/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects. It is kept here so the
// mock app type-checks immediately after dependencies are installed.
